### ISSUE TITLE
Thanks!!!

### ISSUE THREAD

**Issue by ksdavidc** [Mara-Li/obsidian-edit-shortcut#1]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

Just wanted to say thank you. Been hoping for something like this for a long time. It should have been there all along.

### Minimal Reproducible Example

  wheee!!

### Configuration

```JSON
Awesome.
```

### OS

MacOS

### Obsidian information

```bash session
cool
```

### Plugin version

1.3.10

**Comment by Mara-Li** [comment]
<3 thank you!
