### ISSUE TITLE
[Bug]: Duplicated buttons when used in a separate note window

### ISSUE THREAD

**Issue by bumper314** [Mara-Li/obsidian-edit-shortcut#5]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

If I click the edit mode button in a note that's in a separate window (via the "Open current tab in new window" pallet command), duplicate edit mode buttons are created for each click.

![Screen Shot 2024-12-17 at 21 24 42](https://github.com/user-attachments/assets/23e95a5e-83ea-4d2c-99d5-54b7ac72b110)

### How to reproduce ?

- Open a note in a new window (via the "Open current tab in new window" pallet command)
- Click the edit mode button in the upper right
- Observe that duplicate buttons are created each time you click.

### Minimal Reproducible Example

See above

### Configuration

```JSON
There are no settings
```

### Anything else?

Also observed on Windows 10 with no other plugins enabled.

### OS

MacOS

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 18.7.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 14
		1: Front Matter Title v3.10.0
		2: Find orphaned files and broken links v1.10.1
		3: Safe Filename Linter v1.1.4
		4: Linter v1.23.2
		5: Neighbouring Files v1.0.6
		6: Advanced URI v1.44.2
		7: Templater v2.9.1
		8: Update time on edit v2.4.0
		9: Calendar v1.5.10
		10: Evernote Decryptor v2.1.0
		11: Review Notes Plugin v1.1.1
		12: Open Evernote v1.0.0
		13: Editing Mode Hotkey v1.0.0
		14: Edit mode switch v0.0.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Plugin version

0.0.4

**Comment by Mara-Li** [comment]
… 
I forgot to release the fix.
